language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t kale7/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=-true kale7/react-test npm test

after_success:
    - docker build -t kale7/multi-client ./client
    - docker build -t kale7/multi-nginx ./nginx
    - docker build -t kale7/multi-server ./server
    - docker build -t kale7/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push kale7/multi-client
    - docker push kale7/multi-nginx
    - docker push kale7/multi-server
    - docker push kale7/multi-worker